name: Modular Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_maven_scan:
    name: Snyk Maven Scan (JDK 11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Snyk Maven Scan
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarcloud_scan:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    needs: snyk_maven_scan
    steps:
      - uses: actions/checkout@v3

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  zap_scan:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: sonarcloud_scan
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://your-app-url.com'
